/* Automatically generated by adlc */

import * as shapes from './shapes';

export interface CircleAndBlankWall {
  circle1: shapes.Circle;
  circle2: shapes.Circle;
}

export function makeCircleAndBlankWall(
  input: {
    circle1?: shapes.Circle,
    circle2?: shapes.Circle,
  }
): CircleAndBlankWall {
  return {
    circle1: input.circle1 === undefined ? {
      radius: 5,
      color: '#f00',
      center: {
        x: 10,
        y: 10,
      },
    } : input.circle1,
    circle2: input.circle2 === undefined ? {
      radius: 5,
      color: null,
      center: {
        x: 10,
        y: 10,
      },
    } : input.circle2,
  };
}

const CircleAndBlankWall_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"circle1","default":{"kind":"just","value":{"kind":"object","value":{"color":{"just":"#f00"},"radius":5}}},"name":"circle1","type":{"typeRef":{"kind":"reference","value":{"moduleName":"shapes","name":"Circle"}},"parameters":[]}},{"annotations":[],"serializedName":"circle2","default":{"kind":"just","value":{"kind":"object","value":{"color":{"nothing":null},"radius":5}}},"name":"circle2","type":{"typeRef":{"kind":"reference","value":{"moduleName":"shapes","name":"Circle"}},"parameters":[]}}]};

export interface ContemporaryArtGallery {
  artwork: number[];
}

export function makeContemporaryArtGallery(
  input: {
    artwork?: number[],
  }
): ContemporaryArtGallery {
  return {
    artwork: input.artwork === undefined ? [5.6, 7.8, 9] : input.artwork,
  };
}

const ContemporaryArtGallery_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"artwork","default":{"kind":"just","value":{"kind":"array","value":[{"kind":"double","value":5.6},{"kind":"double","value":7.8},{"kind":"integer","value":9}]}},"name":"artwork","type":{"typeRef":{"kind":"primitive","value":"Vector"},"parameters":[{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}]}}]};

export interface Gallery {
  artwork: Picture[];
  moved: Translated<Picture>;
}

export function makeGallery(
  input: {
    artwork: Picture[],
    moved: Translated<Picture>,
  }
): Gallery {
  return {
    artwork: input.artwork,
    moved: input.moved,
  };
}

const Gallery_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"artwork","default":{"kind":"nothing"},"name":"artwork","type":{"typeRef":{"kind":"primitive","value":"Vector"},"parameters":[{"typeRef":{"kind":"reference","value":{"moduleName":"","name":"Picture"}},"parameters":[]}]}},{"annotations":[],"serializedName":"moved","default":{"kind":"nothing"},"name":"moved","type":{"typeRef":{"kind":"reference","value":{"moduleName":"","name":"Translated"}},"parameters":[{"typeRef":{"kind":"reference","value":{"moduleName":"","name":"Picture"}},"parameters":[]}]}}]};

export interface ModernArtGallery {
  circle: shapes.Circle;
}

export function makeModernArtGallery(
  input: {
    circle?: shapes.Circle,
  }
): ModernArtGallery {
  return {
    circle: input.circle === undefined ? {
      radius: 10,
      color: '#f00',
      center: {
        x: 10,
        y: 10,
      },
    } : input.circle,
  };
}

const ModernArtGallery_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"circle","default":{"kind":"just","value":{"kind":"object","value":{"color":{"just":"#f00"},"radius":10}}},"name":"circle","type":{"typeRef":{"kind":"reference","value":{"moduleName":"shapes","name":"Circle"}},"parameters":[]}}]};

interface Picture_Circle {
  kind: 'circle';
  value: shapes.Circle;
}
interface Picture_Composed {
  kind: 'composed';
  value: Picture[];
}
interface Picture_Empty {
  kind: 'empty';
}
interface Picture_Numbers {
  kind: 'numbers';
  value: number;
}
interface Picture_Rectangle {
  kind: 'rectangle';
  value: shapes.Rectangle;
}
interface Picture_Translated {
  kind: 'translated';
  value: Translated<Picture>;
}

export function makePicture_Circle(
  input: {
    kind: 'circle',
    value: shapes.Circle,
  }
): Picture_Circle {
  return {
    kind: input.kind,
    value: input.value,
  };
}
export function makePicture_Composed(
  input: {
    kind: 'composed',
    value: Picture[],
  }
): Picture_Composed {
  return {
    kind: input.kind,
    value: input.value,
  };
}
export function makePicture_Empty(
  input: {
    kind: 'empty',
  }
): Picture_Empty {
  return {
    kind: input.kind,
  };
}
export function makePicture_Numbers(
  input: {
    kind: 'numbers',
    value: number,
  }
): Picture_Numbers {
  return {
    kind: input.kind,
    value: input.value,
  };
}
export function makePicture_Rectangle(
  input: {
    kind: 'rectangle',
    value: shapes.Rectangle,
  }
): Picture_Rectangle {
  return {
    kind: input.kind,
    value: input.value,
  };
}
export function makePicture_Translated(
  input: {
    kind: 'translated',
    value: Translated<Picture>,
  }
): Picture_Translated {
  return {
    kind: input.kind,
    value: input.value,
  };
}

/**
 * Testing doc comment for Picture.
 */
export type Picture = Picture_Circle | Picture_Composed | Picture_Empty | Picture_Numbers | Picture_Rectangle | Picture_Translated;

export type PictureRow = Picture[];

export enum Terminal {
  t1,
  t2,
  t3,
}

/**
 * Testing doc comment for Translated.
 */
export interface Translated<T> {
  layer: number;
  object: T;
  xoffset: number;
  yoffset: number;
}

export function makeTranslated<T>(
  input: {
    layer?: number,
    object: T,
    xoffset?: number,
    yoffset?: number,
  }
): Translated<T> {
  return {
    layer: input.layer === undefined ? 1 : input.layer,
    object: input.object,
    xoffset: input.xoffset === undefined ? 0 : input.xoffset,
    yoffset: input.yoffset === undefined ? 10.5 : input.yoffset,
  };
}

const Translated_AST =
  {"typeParams":["T"],"fields":[{"annotations":[],"serializedName":"xoffset","default":{"kind":"just","value":{"kind":"integer","value":0}},"name":"xoffset","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}},{"annotations":[],"serializedName":"yoffset","default":{"kind":"just","value":{"kind":"double","value":10.5}},"name":"yoffset","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}},{"annotations":[],"serializedName":"layer","default":{"kind":"just","value":{"kind":"integer","value":1}},"name":"layer","type":{"typeRef":{"kind":"primitive","value":"Int32"},"parameters":[]}},{"annotations":[],"serializedName":"object","default":{"kind":"nothing"},"name":"object","type":{"typeRef":{"kind":"typeParam","value":"T"},"parameters":[]}}]};
