/* Automatically generated by adlc */


export interface Circle {
  center: Point;
  color: Color|null;
  radius: number;
}

export function makeCircle(
  input: {
    center?: Point,
    color: Color|null,
    radius: number,
  }
): Circle {
  return {
    center: input.center === undefined ? {
      x: 10,
      y: 10,
    } : input.center,
    color: input.color,
    radius: input.radius,
  };
}

const Circle_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"radius","default":{"kind":"nothing"},"name":"radius","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}},{"annotations":[],"serializedName":"color","default":{"kind":"nothing"},"name":"color","type":{"typeRef":{"kind":"reference","value":{"moduleName":"sys.types","name":"Nullable"}},"parameters":[{"typeRef":{"kind":"reference","value":{"moduleName":"","name":"Color"}},"parameters":[]}]}},{"annotations":[],"serializedName":"center","default":{"kind":"just","value":{"kind":"object","value":{"x":10,"y":10}}},"name":"center","type":{"typeRef":{"kind":"reference","value":{"moduleName":"","name":"Point"}},"parameters":[]}}]};

export type Color = string;

export interface Point {
  x: number;
  y: number;
}

export function makePoint(
  input: {
    x: number,
    y: number,
  }
): Point {
  return {
    x: input.x,
    y: input.y,
  };
}

const Point_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"x","default":{"kind":"nothing"},"name":"x","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}},{"annotations":[],"serializedName":"y","default":{"kind":"nothing"},"name":"y","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}}]};

/**
 * Testing multiline comment.
 * This is the second line.
 */
export interface Rectangle {
  height: number;
  width: number;
}

export function makeRectangle(
  input: {
    height: number,
    width: number,
  }
): Rectangle {
  return {
    height: input.height,
    width: input.width,
  };
}

const Rectangle_AST =
  {"typeParams":[],"fields":[{"annotations":[],"serializedName":"width","default":{"kind":"nothing"},"name":"width","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}},{"annotations":[],"serializedName":"height","default":{"kind":"nothing"},"name":"height","type":{"typeRef":{"kind":"primitive","value":"Double"},"parameters":[]}}]};
