/* Automatically generated by adlc */


interface Either_Left<T1, T2> {
  kind: 'left';
  value: T1;
}
interface Either_Right<T1, T2> {
  kind: 'right';
  value: T2;
}

export type Either<T1, T2> = Either_Left<T1, T2> | Either_Right<T1, T2>;

interface Error_Error<T> {
  kind: 'error';
  value: string;
}
interface Error_Value<T> {
  kind: 'value';
  value: T;
}

export type Error<T> = Error_Error<T> | Error_Value<T>;

export type Map<K, V> = Pair<K, V>[];

interface Maybe_Just<T> {
  kind: 'just';
  value: T;
}
interface Maybe_Nothing<T> {
  kind: 'nothing';
}

export type Maybe<T> = Maybe_Just<T> | Maybe_Nothing<T>;

export interface Pair<T1, T2> {
  v1: T1;
  v2: T2;
}

export function makePair<T1, T2>(
  input: {
    v1: T1,
    v2: T2,
  }
): Pair<T1, T2> {
  return {
    v1: input.v1,
    v2: input.v2,
  };
}

export type Set<T> = T[];
