name: Build and test
on:
  pull_request:
  push:
    branches:
      - master
      - ci-test

jobs:
  build:
    name: CI
    runs-on: macos-latest
    steps:
      - name: test curl
        run: "curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz >/dev/null"

      - name: Setup Stack
        uses: timbod7/setup-stack@master

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('haskell/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build and run tests
        run: "cd haskell; stack build --fast adl-compiler; stack test --fast --no-terminal adl-compiler"
