name: Build and test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('haskell/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build and run tests
        run: "cd haskell; stack build --fast adl-compiler; stack test --fast --no-terminal adl-compiler"
