name: Build and test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHC
        uses: haskell/ghcup-setup@v1
      - run: |
          ghcup install ghc --set 9.8.4
          ghcup install cabal 3.14.2.0


      - name: Clone project
        uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          cd haskell
          cabal update
          cabal build all --enable-tests
          cabal test all
